// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtH3BBVHzGJi7hdv9Q9vFY1N10mA7Li1g',
    appId: '1:935279109591:web:f394faf71ca079ad061792',
    messagingSenderId: '935279109591',
    projectId: 'mata-vision-aid-74a74',
    authDomain: 'mata-vision-aid-74a74.firebaseapp.com',
    storageBucket: 'mata-vision-aid-74a74.firebasestorage.app',
    measurementId: 'G-X3LGTX5RVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2xk6ZnXlyH4hpd1bPSJa_PZyIJ6s2FP4',
    appId: '1:935279109591:android:6c63acf19fabcf19061792',
    messagingSenderId: '935279109591',
    projectId: 'mata-vision-aid-74a74',
    storageBucket: 'mata-vision-aid-74a74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzlQRhh_bosRZ0Zgzhd1JmSeIFmJRD8gw',
    appId: '1:935279109591:ios:9e37c886a2d1f2a1061792',
    messagingSenderId: '935279109591',
    projectId: 'mata-vision-aid-74a74',
    storageBucket: 'mata-vision-aid-74a74.firebasestorage.app',
    iosBundleId: 'com.example.mataVisionAid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzlQRhh_bosRZ0Zgzhd1JmSeIFmJRD8gw',
    appId: '1:935279109591:ios:9e37c886a2d1f2a1061792',
    messagingSenderId: '935279109591',
    projectId: 'mata-vision-aid-74a74',
    storageBucket: 'mata-vision-aid-74a74.firebasestorage.app',
    iosBundleId: 'com.example.mataVisionAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtH3BBVHzGJi7hdv9Q9vFY1N10mA7Li1g',
    appId: '1:935279109591:web:d4b7f36a63aa74b0061792',
    messagingSenderId: '935279109591',
    projectId: 'mata-vision-aid-74a74',
    authDomain: 'mata-vision-aid-74a74.firebaseapp.com',
    storageBucket: 'mata-vision-aid-74a74.firebasestorage.app',
    measurementId: 'G-NXVYRJDY9V',
  );
}
